version: '3'
services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_container
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=testing_net
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql

volumes:
  db: